### ISSUE TITLE
Provide more opinionated guidance for changelog

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/auto-maintenance#252]
According to

https://github.com/linux-system-roles/auto-maintenance/blob/0f7759befdd3f9f748086052e520256a74b9bc46/role-make-version-changelog.sh#L155

it is ok to mention changes to the CI or testing in the changelog. In my opinion, this is too much noise. The changelog should contain only user-facing changes and the other section seems to be the section to fit things such as
- updates to documentation
- updates to examples
- deprecations (for example related to conscious language)

**Comment by nhosoi** [comment]
Thank you for opening this issue, @tyll. I have one question...

I wonder if `updates to examples` could include updating test playbooks? (I'm hoping it. :) I see a possibility to release a new role that only contains some CI-related fixes which are required in the new build and the downstream testing. In that case, we are to make a changelog that only contains the CI fix with a new version number `#.#.#++`. Would it be acceptable in your thoughts?

**Comment by tyll** [comment]
Yes, in that case it should clearly state (IMHO) that the update only exists for this case, so that users know they don't need to consider the update. AFAIK, there is nobody besides us doing any downstream packaging or running the tests.

**Comment by richm** [comment]
> Yes, in that case it should clearly state (IMHO) that the update only exists for this case, so that users know they don't need to consider the update. AFAIK, there is nobody besides us doing any downstream packaging or running the tests.

Right.  What we've done in this case in the past is to have an update which only has an `### Other Changes` section with the entry `- no user-visible changes` https://github.com/linux-system-roles/auto-maintenance/blob/master/lsr_role2collection/COLLECTION_CHANGELOG.md#1341---2023-02-02

**Comment by nhosoi** [comment]
@tyll, @richm, I've submitted a PR including your suggestions (I hope :)
https://github.com/linux-system-roles/auto-maintenance/pull/253
Could you please take a look? Thanks!
